/-
Copyright 2026 Kenta Kitamura (KitaKen1).
-/
import Funk.MainTheorems
import FormalConjecturesUtil.Answer
import FormalConjecturesUtil.Attributes.Basic

/-!
# The Formal Conjectures targets, proved

Generated by scripts/make_final_theorems.py from the two FClikelean files.
Their geometric definitions and theorem statements are copied verbatim;
only the proof slots are filled, using the verified core theorems.
-/

open MeasureTheory
open scoped ENNReal

namespace FunkVolume

/-- A compact convex body, symmetric about the origin, with nonempty interior. -/
def IsSymmetricConvexBody {n : ℕ} (K : Set (Fin n → ℝ)) : Prop :=
  IsCompact K ∧ Convex ℝ K ∧ (∀ x ∈ K, -x ∈ K) ∧ 0 ∈ interior K

/-- The polar body with respect to the ordinary coordinate pairing. -/
def coordinatePolar {n : ℕ} (K : Set (Fin n → ℝ)) : Set (Fin n → ℝ) :=
  {y | ∀ x ∈ K, dotProduct y x ≤ 1}

/-- The translated body K - x. -/
def translate {n : ℕ} (K : Set (Fin n → ℝ)) (x : Fin n → ℝ) : Set (Fin n → ℝ) :=
  (fun z => z - x) '' K

/-- Unnormalized Holmes–Thompson Funk volume, using product Lebesgue measure. -/
noncomputable def funkVolume {n : ℕ} (K : Set (Fin n → ℝ)) (τ : ℝ) : ℝ≥0∞ :=
  ∫⁻ x in ((fun y => τ • y) '' K), volume (coordinatePolar (translate K x))

/-- The numerical lower bound in the symmetric Funk-volume conjecture
[FVW23, Conjecture 1.1], together with finiteness. The answer is affirmative [Ki26]. -/
@[category research solved, AMS 52,
    formal_proof using lean4 at "https://github.com/KitaKen1/funk-volume-kalai-flags/blob/main/lean/FinalTheorems.lean"]
theorem symmetricFunkVolume :
    answer(True) ↔
      ∀ (n : ℕ), 1 ≤ n → ∀ (K : Set (Fin n → ℝ)),
        IsSymmetricConvexBody K → ∀ τ : ℝ, 0 < τ → τ < 1 →
          funkVolume K τ < ⊤ ∧
            ENNReal.ofReal ((4 * Real.artanh τ) ^ n / (n.factorial : ℝ)) ≤
              funkVolume K τ := by
  constructor
  · intro _
    exact Funk.symmetricFunk_lower_bound
  · intro _
    trivial

end FunkVolume

namespace Funk.FormalConjectures

/-- A compact convex body, symmetric about the origin, with nonempty interior. -/
def IsSymmetricConvexBody {n : ℕ} (K : Set (Fin n → ℝ)) : Prop :=
  IsCompact K ∧ Convex ℝ K ∧ (∀ x ∈ K, -x ∈ K) ∧ 0 ∈ interior K

/-- A polytope is the convex hull of finitely many points. -/
def IsFinitePolytope {n : ℕ} (P : Set (Fin n → ℝ)) : Prop :=
  ∃ vertices : Finset (Fin n → ℝ), P = convexHull ℝ (vertices : Set (Fin n → ℝ))

/-- A complete flag consists of one nonempty proper face in each dimension,
ordered by strict inclusion. Nonemptiness excludes the empty face. -/
structure FullFlag {n : ℕ} (P : Set (Fin n → ℝ)) where
  faces : Fin n → Set (Fin n → ℝ)
  nonempty : ∀ i, (faces i).Nonempty
  convex : ∀ i, Convex ℝ (faces i)
  extreme : ∀ i, IsExtreme ℝ P (faces i)
  proper : ∀ i, faces i ⊂ P
  dimension : ∀ i, Module.finrank ℝ (affineSpan ℝ (faces i)).direction = i.val
  chain : StrictMono faces

/-- The FC flag structure and the flag structure used by the proof have
the same faces and conditions. -/
def fullFlagEquiv {n : ℕ} (P : Set (Fin n → ℝ)) : FullFlag P ≃ Funk.FullFlag P where
  toFun f := ⟨f.faces, f.nonempty, f.convex, f.extreme, f.proper, f.dimension, f.chain⟩
  invFun f := ⟨f.faces, f.nonempty, f.convex, f.extreme, f.proper, f.dimension, f.chain⟩
  left_inv f := by cases f; rfl
  right_inv f := by cases f; rfl

/-- Kalai's full flag conjecture [SZ08, p. 21]: does every centrally symmetric
n-dimensional convex polytope have at least 2^n n! complete flags?
The answer is affirmative [Ki26]. -/
@[category research solved, AMS 52,
    formal_proof using lean4 at "https://github.com/KitaKen1/funk-volume-kalai-flags/blob/main/lean/FinalTheorems.lean"]
theorem kalaiFullFlags :
    answer(True) ↔
      ∀ (n : ℕ), 1 ≤ n → ∀ (P : Set (Fin n → ℝ)),
        IsFinitePolytope P → IsSymmetricConvexBody P →
          Finite (FullFlag P) ∧
            2 ^ n * n.factorial ≤ Nat.card (FullFlag P) := by
  constructor
  · intro _ n hn P hp hP
    have h := Funk.kalai_full_flags n hn P hp hP
    let : Finite (Funk.FullFlag P) := h.1
    let : Finite (FullFlag P) :=
      Finite.of_equiv (Funk.FullFlag P) (fullFlagEquiv P).symm
    refine ⟨inferInstance, ?_⟩
    rw [Nat.card_congr (fullFlagEquiv P)]
    exact h.2
  · intro _
    trivial

end Funk.FormalConjectures

#check FunkVolume.symmetricFunkVolume
#print axioms FunkVolume.symmetricFunkVolume
#check Funk.FormalConjectures.kalaiFullFlags
#print axioms Funk.FormalConjectures.kalaiFullFlags
