"""Copy the FC definitions and theorem statements; fill only their proof slots."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[2]
LEAN = ROOT / "lean"

FLAG_EQUIV = '''/-- The FC flag structure and the flag structure used by the proof have
the same faces and conditions. -/
def fullFlagEquiv {n : ℕ} (P : Set (Fin n → ℝ)) : FullFlag P ≃ Funk.FullFlag P where
  toFun f := ⟨f.faces, f.nonempty, f.convex, f.extreme, f.proper, f.dimension, f.chain⟩
  invFun f := ⟨f.faces, f.nonempty, f.convex, f.extreme, f.proper, f.dimension, f.chain⟩
  left_inv f := by cases f; rfl
  right_inv f := by cases f; rfl

'''

KALAI_PROOF = '''  constructor
  · intro _ n hn P hp hP
    have h := Funk.kalai_full_flags n hn P hp hP
    let : Finite (Funk.FullFlag P) := h.1
    let : Finite (FullFlag P) :=
      Finite.of_equiv (Funk.FullFlag P) (fullFlagEquiv P).symm
    refine ⟨inferInstance, ?_⟩
    rw [Nat.card_congr (fullFlagEquiv P)]
    exact h.2
  · intro _
    trivial'''

FUNK_PROOF = '''  constructor
  · intro _
    exact Funk.symmetricFunk_lower_bound
  · intro _
    trivial'''


def generate():
    result = '''/-
Copyright 2026 Kenta Kitamura (KitaKen1).
-/
import Funk.MainTheorems
import FormalConjecturesUtil.Answer
import FormalConjecturesUtil.Attributes.Basic

/-!
# The Formal Conjectures targets, proved

Generated by scripts/make_final_theorems.py from the two FClikelean files.
Their geometric definitions and theorem statements are copied verbatim;
only the proof slots are filled, using the verified core theorems.
-/

'''
    for filename, marker, proof in [
        ("SymmetricFunkVolume.lean", "open MeasureTheory", FUNK_PROOF),
        ("KalaiFullFlags.lean", "namespace Funk.FormalConjectures", KALAI_PROOF),
    ]:
        source = (ROOT / "FClikelean" / filename).read_text()
        body = source[source.index(marker):]
        if body.count("  sorry\n") != 1:
            raise ValueError(f"Expected one proof slot: {filename}")
        body = body.replace("  sorry\n", proof + "\n")
        if filename == "KalaiFullFlags.lean":
            at = body.index("/-- Kalai's full flag conjecture")
            body = body[:at] + FLAG_EQUIV + body[at:]
        result += body + "\n"
    result += '''#check FunkVolume.symmetricFunkVolume
#print axioms FunkVolume.symmetricFunkVolume
#check Funk.FormalConjectures.kalaiFullFlags
#print axioms Funk.FormalConjectures.kalaiFullFlags
'''
    return result.encode()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = LEAN / "FinalTheorems.lean"
    data = generate()
    if args.check:
        if path.read_bytes() != data:
            raise SystemExit("FinalTheorems.lean differs from the FC statements")
    else:
        path.write_bytes(data)
    print("FC final theorems: " + ("regeneration matches" if args.check else "generated"))
